"""
A script to print 6 different star patterns to the console.
Each pattern is generated by its own function.
"""

def draw_right_triangle(size):
    """
    Prints a right triangle.
    *
    * *
    * * *
    * * * *
    """
    print("--- 1. Right Triangle ---")
    for i in range(1, size + 1):
        print("* " * i)
    print("\n")

def draw_inverted_right_triangle(size):
    """
    Prints an inverted right triangle.
    * * * *
    * * *
    * *
    *
    """
    print("--- 2. Inverted Right Triangle ---")
    for i in range(size, 0, -1):
        print("* " * i)
    print("\n")

def draw_pyramid(size):
    """
    Prints a pyramid (centered triangle).
       * * *
     * * *
    * * * *
    """
    print("--- 3. Pyramid ---")
    for i in range(1, size + 1):
        spaces = " " * (size - i)
        stars = "* " * i
        print(spaces + stars)
    print("\n")

def draw_inverted_pyramid(size):
    """
    Prints an inverted pyramid.
    * * * *
     * * *
      * *
       * """
    print("--- 4. Inverted Pyramid ---")
    for i in range(size, 0, -1):
        spaces = " " * (size - i)
        stars = "* " * i
        print(spaces + stars)
    print("\n")

def draw_diamond(size):
    """
    Prints a diamond shape.
       * * *
     * * *
    * * * *
     * * *
      * *
       * """
    print("--- 5. Diamond ---")
    # Top half (Pyramid)
    for i in range(1, size + 1):
        print(" " * (size - i) + "* " * i)
    # Bottom half (Inverted Pyramid, starting from size-1)
    for i in range(size - 1, 0, -1):
        print(" " * (size - i) + "* " * i)
    print("\n")

def draw_hollow_square(size):
    """
    Prints a hollow square.
    * * * * *
    * *
    * *
    * *
    * * * * *
    """
    print("--- 6. Hollow Square ---")
    for i in range(size):
        if i == 0 or i == size - 1:
            # First or last row
            print("* " * size)
        else:
            # Middle rows
            hollow_spaces = "  " * (size - 2)
            print(f"* {hollow_spaces}* ")
    print("\n")


def main():
    """
    Main function to run all pattern drawings.
    """
    # You can change this one number to make all patterns bigger or smaller
    pattern_size = 7
    
    draw_right_triangle(pattern_size)
    draw_inverted_right_triangle(pattern_size)
    draw_pyramid(pattern_size)
    draw_inverted_pyramid(pattern_size)
    draw_diamond(pattern_size)
    draw_hollow_square(pattern_size)

if __name__ == "__main__":
    main()